language: bash

script:
  - make test

python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y texlive
  - sudo apt-get install -y latexdiff
  - sudo apt-get install -y asymptote
  - sudo apt-get install -y gnuplot
  - sudo apt-get install -y git
  - git submodule init
  - git submodule update
  - sudo pip install matplotlib
